"use client"

import { useState, useEffect } from "react"

const translations = {
  en: {
    // Dashboard
    dashboard: "Dashboard",
    welcome: "Welcome Back",
    projects: "Projects",
    accounts: "Accounts",
    dailyTasks: "Daily Tasks",
    settings: "Settings",
    totalProjects: "Total Projects",
    activeAccounts: "Active Accounts",
    pendingTasks: "Pending Tasks",
    recentProjects: "Recent Projects",
    todayTasks: "Today's Tasks",
  projectManager: "Project Manager",
  taskOverview: "Task Overview",
  reports: "Reports",
  codeComponents: "Code Components",
  emailSettings: "Email Settings",
  offline: "Offline",
  loading: "Loading...",
  errorLoading: "Error loading data. Please refresh the page.",
  today: "Today",
  cancel: "Cancel",

    // Dashboard enhancements
    avgRating: "Avg Rating",
    across: "across",
    requiresAttention: "Requires Attention",
    highPriorityTasks: "high priority tasks",
    urgent: "Urgent",
    review: "Review",
    projectProgress: "Project Progress",
    recentActivity: "Recent Activity",
    noActiveProjects: "No active projects",
    noRecentActivity: "No recent activity",
    todaySchedule: "Today's Schedule",
    noTasksToday: "No tasks scheduled for today",
    quickActions: "Quick Actions",
    newAccount: "New Account",

    // Projects
    projectManagement: "Project Management",
    newProject: "New Project",
    addNewProject: "Add New Project",
    editProject: "Edit Project",
    fillProjectDetails: "Fill in the project details below",
    projectName: "Project Name",
    enterProjectName: "Enter project name",
    domain: "Domain",
    figmaLink: "Figma Link",
    description: "Description",
    projectDescription: "Project description",
    status: "Status",
    active: "Active",
    paused: "Paused",
    completed: "Completed",
    cancelled: "Cancelled",
    updateProject: "Update Project",
    createProject: "Create Project",
    existingProjects: "Existing Projects",
    manageYourProjects: "Manage your existing projects",
    noProjectsYet: "No projects created yet",

    // Accounts
    accountManagement: "Account Management",
    addNewAccount: "Add New Account",
    createAccountForProject: "Create a new account for your project",
    project: "Project",
    selectProject: "Select a project",
    website: "Website",
    username: "Username",
    enterUsername: "Enter username",
    password: "Password",
    enterPassword: "Enter password",
    email: "Email",
    notes: "Notes",
    additionalNotes: "Additional notes",
    createAccount: "Create Account",
    savedAccounts: "Saved Accounts",
    manageYourAccounts: "Manage your saved accounts",
    noAccountsYet: "No accounts saved yet",

    // Tasks
    totalTasks: "Total Tasks",
    pending: "Pending",
    addNewTask: "Add New Task",
    createTaskForToday: "Create a new task for today",
    taskTitle: "Task Title",
    enterTaskTitle: "Enter task title",
    taskDescription: "Task description",
    priority: "Priority",
    low: "Low",
    medium: "Medium",
    high: "High",
    estimatedTime: "Estimated Time",
    addTask: "Add Task",
    tasksForToday: "Tasks for today",
    tasksFor: "Tasks for",
    noTasksForThisDay: "No tasks for this day",

    // Settings
    languageAndTheme: "Language & Theme",
    customizeAppearance: "Customize the app's appearance",
    language: "Language",
    theme: "Theme",
    light: "Light",
    dark: "Dark",
    system: "System",
    customColors: "Custom Colors",
    personalizeColors: "Personalize your color scheme",
    primaryColor: "Primary Color",
    secondaryColor: "Secondary Color",
    accentColor: "Accent Color",
    backgroundColor: "Background Color",
    applyColors: "Apply Colors",
    colorsAppliedSuccessfully: "Colors applied successfully!",
    notifications: "Notifications",
    manageNotificationSettings: "Manage your notification preferences",
    emailNotifications: "Email Notifications",
    receiveEmailUpdates: "Receive email updates",
    desktopNotifications: "Desktop Notifications",
    showDesktopAlerts: "Show desktop alerts",
    taskNotifications: "Task Notifications",
    remindTaskDeadlines: "Remind about task deadlines",
    dataManagement: "Data Management",
    backupAndRestore: "Backup and restore your data",
    exportData: "Export Data",
    importData: "Import Data",
    importFromFile: "Import from File",
    dataImportedSuccessfully: "Data imported successfully!",
    errorImportingData: "Error importing data. Please check the file format.",

    // Email Composer
    emailComposer: "Email Composer",
    composeEmail: "Compose Email",
    emailTemplates: "Email Templates",
    to: "To",
    cc: "CC",
    enterEmailSubject: "Enter email subject",
    emailContent: "Email Content",
    enterEmailContent: "Enter your email content",
    selectedAccounts: "Selected Accounts",
    sendEmail: "Send Email",
    includeAccounts: "Include Accounts",
    selectAccountsToInclude: "Select accounts to include in email",
    filterByProject: "Filter by Project",
    noAccountsFound: "No accounts found",
    savedEmailTemplates: "Saved Email Templates",
    manageYourEmailTemplates: "Manage your email templates",
    emailTemplateDesigner: "Email Template Designer",
    createCustomEmailTemplate: "Create custom email template",
    accountCredentials: "Account Credentials",
    generalEmail: "General Email",
    clear: "Clear",
    useTheseVariablesInEmail: "Use these variables in your email",
    yourName: "Your Name",
    accountVariables: "Account Variables",
    accountInfo: "Account Information",
    progress: "Progress",
    projectStatus: "Project Status",
    recentTasks: "Recent Tasks",
    nextSteps: "Next Steps",
    noEmailTemplatesYet: "No email templates created yet",
    useTemplate: "Use Template",
    viewDetails: "View details",
    noDescription: "No description",
    taskDetails: "Task details",
    taskDetailsDescription: "Full information about this task",
    taskDate: "Task date",
    actualTime: "Actual Time",
    createdAt: "Created at",
    updatedAt: "Updated at",
    noTasksInList: "No tasks in this list",
    noDate: "No date",
    databaseConnectionError: "Cannot connect to database or no data available. Please check database connection.",
    databaseConnected: "Database connected successfully",
    total: "total",
    todayHasTasks: "Today has",
    todo: "To Do",
    inProgress: "In Progress", 
    notEstimated: "Not estimated",
    notCompleted: "Not completed",
    noInformation: "No information",
    taskCompleted: "Task completed",
    taskNotCompleted: "Task not completed",
    
    // Additional common translations
    save: "Save",
    edit: "Edit",
    delete: "Delete",
    create: "Create",
    update: "Update",
    search: "Search",
    filter: "Filter",
    all: "All",
    none: "None",
    yes: "Yes",
    no: "No",
    confirm: "Confirm",
    back: "Back",
    next: "Next",
    previous: "Previous",
    close: "Close",
    open: "Open",
    view: "View",
    hide: "Hide",
    show: "Show",
    expand: "Expand",
    collapse: "Collapse",
    refresh: "Refresh",
    reload: "Reload",
    copy: "Copy",
    paste: "Paste",
    cut: "Cut",
    selectAll: "Select All",
    download: "Download",
    upload: "Upload",
    print: "Print",
    share: "Share",
    send: "Send",
    receive: "Receive",
    submit: "Submit",
    resetData: "Reset",
    clearData: "Clear",
    apply: "Apply",
    approve: "Approve",
    reject: "Reject",
    enable: "Enable",
    disable: "Disable",
    activate: "Activate",
    deactivate: "Deactivate",
    start: "Start",
    stop: "Stop",
    pause: "Pause",
    resume: "Resume",
    finish: "Finish",
    complete: "Complete",
    incomplete: "Incomplete",
    success: "Success",
    error: "Error",
    warning: "Warning",
    info: "Information",
    loadingData: "Loading...",
    saving: "Saving...",
    updating: "Updating...",
    creating: "Creating...",
    deleting: "Deleting...",
    processing: "Processing...",
    uploading: "Uploading...",
    downloading: "Downloading...",
    connecting: "Connecting...",
    disconnecting: "Disconnecting...",
    online: "Online",
    offlineMode: "Offline",
    connected: "Connected",
    disconnected: "Disconnected",
    available: "Available",
    unavailable: "Unavailable",
    required: "Required",
    optional: "Optional",
    invalid: "Invalid",
    valid: "Valid",
    empty: "Empty",
    full: "Full",
    new: "New",
    old: "Old",
    recent: "Recent",
    latest: "Latest",
    oldest: "Oldest",
    first: "First",
    last: "Last",
    home: "Home",
    menu: "Menu",
    appSettings: "Settings",
    preferences: "Preferences",
    options: "Options",
    help: "Help",
    about: "About",
    contact: "Contact",
    support: "Support",
    feedback: "Feedback",
    report: "Report",
    bug: "Bug",
    feature: "Feature",
    version: "Version",
    updateApp: "Update",
    upgrade: "Upgrade",
    downgrade: "Downgrade",
    install: "Install",
    uninstall: "Uninstall",
    configure: "Configure",
    setup: "Setup",
    initialize: "Initialize",
    resetApp: "Reset",
    restore: "Restore",
    backup: "Backup",
    recover: "Recover",
    sync: "Sync",
    merge: "Merge",
    split: "Split",
    join: "Join",
    leave: "Leave",
    enter: "Enter",
    exit: "Exit",
    login: "Login",
    logout: "Logout",
    signin: "Sign In",
    signout: "Sign Out",
    signup: "Sign Up",
    register: "Register",
    unregister: "Unregister",
    authenticate: "Authenticate",
    authorize: "Authorize",
    unauthorize: "Unauthorize",
    grant: "Grant",
    revoke: "Revoke",
    allow: "Allow",
    deny: "Deny",
    block: "Block",
    unblock: "Unblock",
    lock: "Lock",
    unlock: "Unlock",
    secure: "Secure",
    unsecure: "Unsecure",
    encrypt: "Encrypt",
    decrypt: "Decrypt",
    hash: "Hash",
    verify: "Verify",
    validate: "Validate",
    invalidate: "Invalidate"
  },
  vi: {
    // Dashboard
    dashboard: "Bảng điều khiển",
    welcome: "Chào mừng trở lại",
    projects: "Dự án",
    accounts: "Tài khoản",
    dailyTasks: "Công việc hàng ngày",
    settings: "Cài đặt",
    totalProjects: "Tổng số dự án",
    activeAccounts: "Tài khoản hoạt động",
    pendingTasks: "Công việc chờ xử lý",
    recentProjects: "Dự án gần đây",
    todayTasks: "Công việc hôm nay",
  projectManager: "Quản lý dự án",
  taskOverview: "Tổng quan Task",
  reports: "Báo cáo",
  codeComponents: "Thành phần Code",
  emailSettings: "Cài đặt Email",
  offline: "Ngoại tuyến",
  loading: "Đang tải...",
  errorLoading: "Lỗi tải dữ liệu. Vui lòng tải lại trang.",
  today: "Hôm nay",
  cancel: "Hủy",

    // Dashboard enhancements
    avgRating: "Đánh giá TB",
    across: "trên",
    requiresAttention: "Cần chú ý",
    highPriorityTasks: "công việc ưu tiên cao",
    urgent: "Khẩn cấp",
    review: "Xem xét",
    projectProgress: "Tiến độ dự án",
    recentActivity: "Hoạt động gần đây",
    noActiveProjects: "Không có dự án đang hoạt động",
    noRecentActivity: "Không có hoạt động gần đây",
    todaySchedule: "Lịch trình hôm nay",
    noTasksToday: "Không có công việc nào hôm nay",
    quickActions: "Thao tác nhanh",
    newAccount: "Tài khoản mới",

    // Projects
    projectManagement: "Quản lý dự án",
    newProject: "Dự án mới",
    addNewProject: "Thêm dự án mới",
    editProject: "Chỉnh sửa dự án",
    fillProjectDetails: "Điền thông tin chi tiết dự án bên dưới",
    projectName: "Tên dự án",
    enterProjectName: "Nhập tên dự án",
    domain: "Tên miền",
    figmaLink: "Liên kết Figma",
    description: "Mô tả",
    projectDescription: "Mô tả dự án",
    status: "Trạng thái",
    active: "Hoạt động",
    paused: "Tạm dừng",
    completed: "Hoàn thành",
    cancelled: "Đã hủy",
    updateProject: "Cập nhật dự án",
    createProject: "Tạo dự án",
    existingProjects: "Dự án hiện có",
    manageYourProjects: "Quản lý các dự án hiện có của bạn",
    noProjectsYet: "Chưa có dự án nào được tạo",

    // Accounts
    accountManagement: "Quản lý tài khoản",
    addNewAccount: "Thêm tài khoản mới",
    createAccountForProject: "Tạo tài khoản mới cho dự án của bạn",
    project: "Dự án",
    selectProject: "Chọn dự án",
    website: "Website",
    username: "Tên đăng nhập",
    enterUsername: "Nhập tên đăng nhập",
    password: "Mật khẩu",
    enterPassword: "Nhập mật khẩu",
    email: "Email",
    notes: "Ghi chú",
    additionalNotes: "Ghi chú bổ sung",
    createAccount: "Tạo tài khoản",
    savedAccounts: "Tài khoản đã lưu",
    manageYourAccounts: "Quản lý các tài khoản đã lưu",
    noAccountsYet: "Chưa có tài khoản nào được lưu",

    // Tasks
    totalTasks: "Tổng công việc",
    pending: "Chờ xử lý",
    addNewTask: "Thêm công việc mới",
    createTaskForToday: "Tạo công việc mới cho hôm nay",
    taskTitle: "Tiêu đề công việc",
    enterTaskTitle: "Nhập tiêu đề công việc",
    taskDescription: "Mô tả công việc",
    priority: "Độ ưu tiên",
    low: "Thấp",
    medium: "Trung bình",
    high: "Cao",
    estimatedTime: "Thời gian ước tính",
    addTask: "Thêm công việc",
    tasksForToday: "Công việc hôm nay",
    tasksFor: "Công việc cho",
    noTasksForThisDay: "Không có công việc nào cho ngày này",

    // Settings
    languageAndTheme: "Ngôn ngữ & Giao diện",
    customizeAppearance: "Tùy chỉnh giao diện ứng dụng",
    language: "Ngôn ngữ",
    theme: "Giao diện",
    light: "Sáng",
    dark: "Tối",
    system: "Hệ thống",
    customColors: "Màu tùy chỉnh",
    personalizeColors: "Cá nhân hóa bảng màu của bạn",
    primaryColor: "Màu chính",
    secondaryColor: "Màu phụ",
    accentColor: "Màu nhấn",
    backgroundColor: "Màu nền",
    applyColors: "Áp dụng màu",
    colorsAppliedSuccessfully: "Đã áp dụng màu thành công!",
    notifications: "Thông báo",
    manageNotificationSettings: "Quản lý tùy chọn thông báo",
    emailNotifications: "Thông báo Email",
    receiveEmailUpdates: "Nhận cập nhật qua email",
    desktopNotifications: "Thông báo Desktop",
    showDesktopAlerts: "Hiển thị cảnh báo desktop",
    taskNotifications: "Thông báo công việc",
    remindTaskDeadlines: "Nhắc nhở về deadline công việc",
    dataManagement: "Quản lý dữ liệu",
    backupAndRestore: "Sao lưu và khôi phục dữ liệu",
    exportData: "Xuất dữ liệu",
    importData: "Nhập dữ liệu",
    importFromFile: "Nhập từ file",
    dataImportedSuccessfully: "Dữ liệu đã được nhập thành công!",
    errorImportingData: "Lỗi khi nhập dữ liệu. Vui lòng kiểm tra định dạng file.",

    // Email Composer
    emailComposer: "Soạn Email",
    composeEmail: "Soạn Email",
    emailTemplates: "Mẫu Email",
    to: "Đến",
    cc: "CC",
    enterEmailSubject: "Nhập chủ đề email",
    emailContent: "Nội dung Email",
    enterEmailContent: "Nhập nội dung email",
    selectedAccounts: "Tài khoản đã chọn",
    sendEmail: "Gửi Email",
    includeAccounts: "Bao gồm tài khoản",
    selectAccountsToInclude: "Chọn tài khoản để bao gồm trong email",
    filterByProject: "Lọc theo dự án",
    noAccountsFound: "Không tìm thấy tài khoản",
    savedEmailTemplates: "Mẫu Email đã lưu",
    manageYourEmailTemplates: "Quản lý mẫu email của bạn",
    emailTemplateDesigner: "Thiết kế mẫu Email",
    createCustomEmailTemplate: "Tạo mẫu email tùy chỉnh",
    accountCredentials: "Thông tin tài khoản",
    generalEmail: "Email chung",
    clear: "Xóa",
    useTheseVariablesInEmail: "Sử dụng các biến này trong email",
    yourName: "Tên của bạn",
    accountVariables: "Biến tài khoản",
    accountInfo: "Thông tin tài khoản",
    progress: "Tiến độ",
    projectStatus: "Trạng thái dự án",
    recentTasks: "Công việc gần đây",
    nextSteps: "Bước tiếp theo",
    noEmailTemplatesYet: "Chưa có mẫu email nào được tạo",
    useTemplate: "Sử dụng mẫu",
    viewDetails: "Xem chi tiết",
    noDescription: "Không có mô tả",
    taskDetails: "Chi tiết Task",
    taskDetailsDescription: "Thông tin đầy đủ về task này",
    taskDate: "Ngày thực hiện",
    actualTime: "Thời gian thực tế",
    createdAt: "Ngày tạo",
    updatedAt: "Cập nhật lần cuối",
    noTasksInList: "Không có task nào trong danh sách này",
    noDate: "Chưa có ngày",
    databaseConnectionError: "Không thể kết nối đến database hoặc chưa có dữ liệu. Vui lòng kiểm tra kết nối database.",
    databaseConnected: "Đã kết nối database thành công",
    total: "tổng cộng",
    todayHasTasks: "Hôm nay có",
    todo: "Cần làm",
    inProgress: "Đang làm",
    notEstimated: "Chưa ước tính", 
    notCompleted: "Chưa hoàn thành",
    noInformation: "Không có thông tin",
    taskCompleted: "Task đã hoàn thành",
    taskNotCompleted: "Task chưa hoàn thành",
    
    // Additional Vietnamese translations
    save: "Lưu",
    edit: "Chỉnh sửa",
    delete: "Xóa",
    create: "Tạo",
    update: "Cập nhật",
    search: "Tìm kiếm",
    filter: "Lọc",
    all: "Tất cả",
    none: "Không có",
    yes: "Có",
    no: "Không",
    confirm: "Xác nhận",
    back: "Quay lại",
    next: "Tiếp theo",
    previous: "Trước đó",
    close: "Đóng",
    open: "Mở",
    view: "Xem",
    hide: "Ẩn",
    show: "Hiển thị",
    expand: "Mở rộng",
    collapse: "Thu gọn",
    refresh: "Làm mới",
    reload: "Tải lại",
    copy: "Sao chép",
    paste: "Dán",
    cut: "Cắt",
    selectAll: "Chọn tất cả",
    download: "Tải xuống",
    upload: "Tải lên",
    print: "In",
    share: "Chia sẻ",
    send: "Gửi",
    receive: "Nhận",
    submit: "Gửi",
    resetData: "Đặt lại",
    clearData: "Xóa",
    apply: "Áp dụng",
    approve: "Phê duyệt",
    reject: "Từ chối",
    enable: "Bật",
    disable: "Tắt",
    activate: "Kích hoạt",
    deactivate: "Hủy kích hoạt",
    start: "Bắt đầu",
    stop: "Dừng",
    pause: "Tạm dừng",
    resume: "Tiếp tục",
    finish: "Kết thúc",
    complete: "Hoàn thành",
    incomplete: "Chưa hoàn thành",
    success: "Thành công",
    error: "Lỗi",
    warning: "Cảnh báo",
    info: "Thông tin",
    loadingData: "Đang tải...",
    saving: "Đang lưu...",
    updating: "Đang cập nhật...",
    creating: "Đang tạo...",
    deleting: "Đang xóa...",
    processing: "Đang xử lý...",
    uploading: "Đang tải lên...",
    downloading: "Đang tải xuống...",
    connecting: "Đang kết nối...",
    disconnecting: "Đang ngắt kết nối...",
    online: "Trực tuyến",
    offlineMode: "Ngoại tuyến",
    connected: "Đã kết nối",
    disconnected: "Đã ngắt kết nối",
    available: "Có sẵn",
    unavailable: "Không có sẵn",
    required: "Bắt buộc",
    optional: "Tùy chọn",
    invalid: "Không hợp lệ",
    valid: "Hợp lệ",
    empty: "Trống",
    full: "Đầy",
    new: "Mới",
    old: "Cũ",
    recent: "Gần đây",
    latest: "Mới nhất",
    oldest: "Cũ nhất",
    first: "Đầu tiên",
    last: "Cuối cùng",
    home: "Trang chủ",
    menu: "Menu",
    appSettings: "Cài đặt",
    preferences: "Tùy chọn",
    options: "Lựa chọn",
    help: "Trợ giúp",
    about: "Giới thiệu",
    contact: "Liên hệ",
    support: "Hỗ trợ",
    feedback: "Phản hồi",
    report: "Báo cáo",
    bug: "Lỗi",
    feature: "Tính năng",
    version: "Phiên bản",
    updateApp: "Cập nhật",
    upgrade: "Nâng cấp",
    downgrade: "Hạ cấp",
    install: "Cài đặt",
    uninstall: "Gỡ cài đặt",
    configure: "Cấu hình",
    setup: "Thiết lập",
    initialize: "Khởi tạo",
    resetApp: "Đặt lại",
    restore: "Khôi phục",
    backup: "Sao lưu",
    recover: "Phục hồi",
    sync: "Đồng bộ",
    merge: "Hợp nhất",
    split: "Tách",
    join: "Tham gia",
    leave: "Rời khỏi",
    enter: "Nhập",
    exit: "Thoát",
    login: "Đăng nhập",
    logout: "Đăng xuất",
    signin: "Đăng nhập",
    signout: "Đăng xuất",
    signup: "Đăng ký",
    register: "Đăng ký",
    unregister: "Hủy đăng ký",
    authenticate: "Xác thực",
    authorize: "Ủy quyền",
    unauthorize: "Hủy ủy quyền",
    grant: "Cấp",
    revoke: "Thu hồi",
    allow: "Cho phép",
    deny: "Từ chối",
    block: "Chặn",
    unblock: "Bỏ chặn",
    lock: "Khóa",
    unlock: "Mở khóa",
    secure: "Bảo mật",
    unsecure: "Không bảo mật",
    encrypt: "Mã hóa",
    decrypt: "Giải mã",
    hash: "Băm",
    verify: "Xác minh",
    validate: "Xác thực",
    invalidate: "Vô hiệu hóa",
    noResults: "Không tìm thấy kết quả",
    resultsFound: "Tìm thấy kết quả",
    searchResults: "Kết quả tìm kiếm",
    created: "Ngày tạo"
  },
}

export function useLanguage() {
  const [language, setLanguage] = useState<"en" | "vi">("vi")

  useEffect(() => {
    const savedLanguage = (typeof window !== 'undefined' && localStorage.getItem("language")) as "en" | "vi" | null
    if (savedLanguage) {
      setLanguage(savedLanguage)
      return
    }
    // Default to Vietnamese for Vietnamese users
    const nav = typeof navigator !== 'undefined' ? navigator.language || "vi" : "vi"
    if (nav.toLowerCase().startsWith("en")) {
      setLanguage("en")
    } else {
      setLanguage("vi") // Default to Vietnamese
    }
  }, [])

  const changeLanguage = (newLanguage: "en" | "vi") => {
    setLanguage(newLanguage)
    localStorage.setItem("language", newLanguage)
  }

  const t = (key: string) => {
    return translations[language][key as keyof (typeof translations)[typeof language]] || key
  }

  return {
    language,
    setLanguage: changeLanguage,
    t,
  }
}
