"use client"

import { useState, useEffect } from "react"

const translations = {
  en: {
    // Dashboard
    dashboard: "Dashboard",
    welcome: "Welcome Back",
    projects: "Projects",
    accounts: "Accounts",
    dailyTasks: "Daily Tasks",
    feedback: "Feedback",
    reports: "Reports",
    settings: "Settings",
    totalProjects: "Total Projects",
    activeAccounts: "Active Accounts",
    pendingTasks: "Pending Tasks",
    newFeedback: "New Feedback",
    recentProjects: "Recent Projects",
    todayTasks: "Today's Tasks",

    // Dashboard enhancements
    avgRating: "Avg Rating",
    across: "across",
    requiresAttention: "Requires Attention",
    highPriorityTasks: "high priority tasks",
    urgent: "Urgent",
    review: "Review",
    projectProgress: "Project Progress",
    recentActivity: "Recent Activity",
    noActiveProjects: "No active projects",
    noRecentActivity: "No recent activity",
    todaySchedule: "Today's Schedule",
    noTasksToday: "No tasks scheduled for today",
    quickActions: "Quick Actions",
    newAccount: "New Account",

    // Projects
    projectManagement: "Project Management",
    newProject: "New Project",
    addNewProject: "Add New Project",
    editProject: "Edit Project",
    fillProjectDetails: "Fill in the project details below",
    projectName: "Project Name",
    enterProjectName: "Enter project name",
    domain: "Domain",
    figmaLink: "Figma Link",
    description: "Description",
    projectDescription: "Project description",
    status: "Status",
    active: "Active",
    paused: "Paused",
    completed: "Completed",
    cancelled: "Cancelled",
    updateProject: "Update Project",
    createProject: "Create Project",
    existingProjects: "Existing Projects",
    manageYourProjects: "Manage your existing projects",
    noProjectsYet: "No projects created yet",

    // Accounts
    accountManagement: "Account Management",
    addNewAccount: "Add New Account",
    createAccountForProject: "Create a new account for your project",
    project: "Project",
    selectProject: "Select a project",
    website: "Website",
    username: "Username",
    enterUsername: "Enter username",
    password: "Password",
    enterPassword: "Enter password",
    email: "Email",
    notes: "Notes",
    additionalNotes: "Additional notes",
    createAccount: "Create Account",
    savedAccounts: "Saved Accounts",
    manageYourAccounts: "Manage your saved accounts",
    noAccountsYet: "No accounts saved yet",

    // Tasks
    totalTasks: "Total Tasks",
    completed: "Completed",
    pending: "Pending",
    addNewTask: "Add New Task",
    createTaskForToday: "Create a new task for today",
    taskTitle: "Task Title",
    enterTaskTitle: "Enter task title",
    taskDescription: "Task description",
    priority: "Priority",
    low: "Low",
    medium: "Medium",
    high: "High",
    estimatedTime: "Estimated Time",
    addTask: "Add Task",
    tasksForToday: "Tasks for today",
    tasksFor: "Tasks for",
    noTasksForThisDay: "No tasks for this day",

    // Feedback
    feedbackSystem: "Feedback System",
    new: "New",
    totalFeedback: "Total Feedback",
    inProgress: "In Progress",
    resolved: "Resolved",
    addNewFeedback: "Add New Feedback",
    recordClientFeedback: "Record feedback from your clients",
    clientName: "Client Name",
    enterClientName: "Enter client name",
    clientEmail: "Client Email",
    subject: "Subject",
    feedbackSubject: "Feedback subject",
    message: "Message",
    feedbackMessage: "Feedback message",
    rating: "Rating",
    star: "star",
    stars: "stars",
    addFeedback: "Add Feedback",
    feedbackList: "Feedback List",
    all: "All",
    resolve: "Resolve",
    noFeedbackFound: "No feedback found",

    // Reports
    reportGenerator: "Report Generator",
    generateReport: "Generate Report",
    configureReportSettings: "Configure your report settings",
    reportType: "Report Type",
    dailyReport: "Daily Report",
    dailyReportDesc: "Tasks and activities for a specific day",
    weeklyReport: "Weekly Report",
    weeklyReportDesc: "Summary of the week's activities",
    projectReport: "Project Report",
    projectReportDesc: "Comprehensive project overview",
    feedbackReport: "Feedback Report",
    feedbackReportDesc: "Client feedback analysis",
    optional: "Optional",
    allProjects: "All Projects",
    fromDate: "From Date",
    toDate: "To Date",
    generateAndDownload: "Generate & Download",
    customTemplate: "Custom Template",
    designCustomReportTemplate: "Design your own report template",
    templateName: "Template Name",
    enterTemplateName: "Enter template name",
    templateStructure: "Template Structure",
    templatePlaceholder: "Enter your custom template structure...",
    availableVariables: "Available Variables",
    projectDomain: "Project Domain",
    taskStatus: "Task Status",
    feedbackRating: "Feedback Rating",
    currentDate: "Current Date",
    saveTemplate: "Save Template",

    // Report Generator enhancements
    manageTemplates: "Manage Templates",
    templateDesigner: "Template Designer",
    reportConfiguration: "Report Configuration",
    exportOptions: "Export Options",
    chooseExportFormat: "Choose export format",
    basicData: "Basic data",
    advancedSpreadsheet: "Advanced spreadsheet",
    documentReport: "Document report",
    printableReport: "Printable report",
    quickGenerate: "Quick Generate",
    generatePDFReport: "Generate PDF Report",
    generateExcelReport: "Generate Excel Report",
    manageYourReportTemplates: "Manage your saved report templates",
    created: "Created",
    use: "Use",
    edit: "Edit",
    noTemplatesYet: "No templates created yet",
    createCustomReportTemplate: "Create your own custom report template",
    loadDefault: "Load Default",
    basicVariables: "Basic Variables",
    projectVariables: "Project Variables",
    loopVariables: "Loop Variables",
    loopThroughTasks: "Loop through all tasks",
    loopThroughFeedbacks: "Loop through all feedbacks",
    loopThroughProjects: "Loop through all projects",
    taskVariables: "Task Variables",
    feedbackVariables: "Feedback Variables",
    useTheseVariablesInTemplate: "Use these variables in your template",

    // Settings
    languageAndTheme: "Language & Theme",
    customizeAppearance: "Customize the app's appearance",
    language: "Language",
    theme: "Theme",
    light: "Light",
    dark: "Dark",
    system: "System",
    customColors: "Custom Colors",
    personalizeColors: "Personalize your color scheme",
    primaryColor: "Primary Color",
    secondaryColor: "Secondary Color",
    accentColor: "Accent Color",
    backgroundColor: "Background Color",
    applyColors: "Apply Colors",
    notifications: "Notifications",
    manageNotificationSettings: "Manage your notification preferences",
    emailNotifications: "Email Notifications",
    receiveEmailUpdates: "Receive email updates",
    desktopNotifications: "Desktop Notifications",
    showDesktopAlerts: "Show desktop alerts",
    feedbackNotifications: "Feedback Notifications",
    notifyNewFeedback: "Notify when new feedback arrives",
    taskNotifications: "Task Notifications",
    remindTaskDeadlines: "Remind about task deadlines",
    dataManagement: "Data Management",
    backupAndRestore: "Backup and restore your data",
    exportData: "Export Data",
    importData: "Import Data",
    importFromFile: "Import from File",
    dataImportedSuccessfully: "Data imported successfully!",
    errorImportingData: "Error importing data. Please check the file format.",

    // Dashboard enhancements
    avgRating: "Avg Rating",
    across: "across",
    requiresAttention: "Requires Attention",
    highPriorityTasks: "high priority tasks",
    urgent: "Urgent",
    review: "Review",
    projectProgress: "Project Progress",
    recentActivity: "Recent Activity",
    noActiveProjects: "No active projects",
    noRecentActivity: "No recent activity",
    todaySchedule: "Today's Schedule",
    noTasksToday: "No tasks scheduled for today",
    quickActions: "Quick Actions",
    newAccount: "New Account",

    // Report Generator enhancements
    manageTemplates: "Manage Templates",
    templateDesigner: "Template Designer",
    reportConfiguration: "Report Configuration",
    exportOptions: "Export Options",
    chooseExportFormat: "Choose export format",
    basicData: "Basic data",
    advancedSpreadsheet: "Advanced spreadsheet",
    documentReport: "Document report",
    printableReport: "Printable report",
    quickGenerate: "Quick Generate",
    generatePDFReport: "Generate PDF Report",
    generateExcelReport: "Generate Excel Report",
    manageYourReportTemplates: "Manage your saved report templates",
    created: "Created",
    use: "Use",
    edit: "Edit",
    noTemplatesYet: "No templates created yet",
    createCustomReportTemplate: "Create your own custom report template",
    loadDefault: "Load Default",
    basicVariables: "Basic Variables",
    projectVariables: "Project Variables",
    loopVariables: "Loop Variables",
    loopThroughTasks: "Loop through all tasks",
    loopThroughFeedbacks: "Loop through all feedbacks",
    loopThroughProjects: "Loop through all projects",
    taskVariables: "Task Variables",
    feedbackVariables: "Feedback Variables",
    useTheseVariablesInTemplate: "Use these variables in your template",

    // Email Composer
    emailComposer: "Email Composer",
    composeEmail: "Compose Email",
    emailTemplates: "Email Templates",
    to: "To",
    cc: "CC",
    enterEmailSubject: "Enter email subject",
    emailContent: "Email Content",
    enterEmailContent: "Enter your email content",
    selectedAccounts: "Selected Accounts",
    sendEmail: "Send Email",
    attachReport: "Attach Report",
    includeAccounts: "Include Accounts",
    selectAccountsToInclude: "Select accounts to include in email",
    filterByProject: "Filter by Project",
    noAccountsFound: "No accounts found",
    savedEmailTemplates: "Saved Email Templates",
    manageYourEmailTemplates: "Manage your email templates",
    emailTemplateDesigner: "Email Template Designer",
    createCustomEmailTemplate: "Create custom email template",
    accountCredentials: "Account Credentials",
    generalEmail: "General Email",
    clear: "Clear",
    useTheseVariablesInEmail: "Use these variables in your email",
    clientName: "Client Name",
    yourName: "Your Name",
    accountVariables: "Account Variables",
    accountInfo: "Account Information",
    reportVariables: "Report Variables",
    progress: "Progress",
    projectStatus: "Project Status",
    recentTasks: "Recent Tasks",
    nextSteps: "Next Steps",
    noEmailTemplatesYet: "No email templates created yet",
    useTemplate: "Use Template",
  },
  vi: {
    // Dashboard
    dashboard: "Bảng điều khiển",
    welcome: "Chào mừng trở lại",
    projects: "Dự án",
    accounts: "Tài khoản",
    dailyTasks: "Công việc hàng ngày",
    feedback: "Phản hồi",
    reports: "Báo cáo",
    settings: "Cài đặt",
    totalProjects: "Tổng số dự án",
    activeAccounts: "Tài khoản hoạt động",
    pendingTasks: "Công việc chờ xử lý",
    newFeedback: "Phản hồi mới",
    recentProjects: "Dự án gần đây",
    todayTasks: "Công việc hôm nay",

    // Dashboard enhancements
    avgRating: "Đánh giá TB",
    across: "trên",
    requiresAttention: "Cần chú ý",
    highPriorityTasks: "công việc ưu tiên cao",
    urgent: "Khẩn cấp",
    review: "Xem xét",
    projectProgress: "Tiến độ dự án",
    recentActivity: "Hoạt động gần đây",
    noActiveProjects: "Không có dự án đang hoạt động",
    noRecentActivity: "Không có hoạt động gần đây",
    todaySchedule: "Lịch trình hôm nay",
    noTasksToday: "Không có công việc nào hôm nay",
    quickActions: "Thao tác nhanh",
    newAccount: "Tài khoản mới",

    // Projects
    projectManagement: "Quản lý dự án",
    newProject: "Dự án mới",
    addNewProject: "Thêm dự án mới",
    editProject: "Chỉnh sửa dự án",
    fillProjectDetails: "Điền thông tin chi tiết dự án bên dưới",
    projectName: "Tên dự án",
    enterProjectName: "Nhập tên dự án",
    domain: "Tên miền",
    figmaLink: "Liên kết Figma",
    description: "Mô tả",
    projectDescription: "Mô tả dự án",
    status: "Trạng thái",
    active: "Hoạt động",
    paused: "Tạm dừng",
    completed: "Hoàn thành",
    cancelled: "Đã hủy",
    updateProject: "Cập nhật dự án",
    createProject: "Tạo dự án",
    existingProjects: "Dự án hiện có",
    manageYourProjects: "Quản lý các dự án hiện có của bạn",
    noProjectsYet: "Chưa có dự án nào được tạo",

    // Accounts
    accountManagement: "Quản lý tài khoản",
    addNewAccount: "Thêm tài khoản mới",
    createAccountForProject: "Tạo tài khoản mới cho dự án của bạn",
    project: "Dự án",
    selectProject: "Chọn dự án",
    website: "Website",
    username: "Tên đăng nhập",
    enterUsername: "Nhập tên đăng nhập",
    password: "Mật khẩu",
    enterPassword: "Nhập mật khẩu",
    email: "Email",
    notes: "Ghi chú",
    additionalNotes: "Ghi chú bổ sung",
    createAccount: "Tạo tài khoản",
    savedAccounts: "Tài khoản đã lưu",
    manageYourAccounts: "Quản lý các tài khoản đã lưu",
    noAccountsYet: "Chưa có tài khoản nào được lưu",

    // Tasks
    totalTasks: "Tổng công việc",
    completed: "Đã hoàn thành",
    pending: "Chờ xử lý",
    addNewTask: "Thêm công việc mới",
    createTaskForToday: "Tạo công việc mới cho hôm nay",
    taskTitle: "Tiêu đề công việc",
    enterTaskTitle: "Nhập tiêu đề công việc",
    taskDescription: "Mô tả công việc",
    priority: "Độ ưu tiên",
    low: "Thấp",
    medium: "Trung bình",
    high: "Cao",
    estimatedTime: "Thời gian ước tính",
    addTask: "Thêm công việc",
    tasksForToday: "Công việc hôm nay",
    tasksFor: "Công việc cho",
    noTasksForThisDay: "Không có công việc nào cho ngày này",

    // Feedback
    feedbackSystem: "Hệ thống phản hồi",
    new: "Mới",
    totalFeedback: "Tổng phản hồi",
    inProgress: "Đang xử lý",
    resolved: "Đã giải quyết",
    addNewFeedback: "Thêm phản hồi mới",
    recordClientFeedback: "Ghi lại phản hồi từ khách hàng",
    clientName: "Tên khách hàng",
    enterClientName: "Nhập tên khách hàng",
    clientEmail: "Email khách hàng",
    subject: "Chủ đề",
    feedbackSubject: "Chủ đề phản hồi",
    message: "Tin nhắn",
    feedbackMessage: "Nội dung phản hồi",
    rating: "Đánh giá",
    star: "sao",
    stars: "sao",
    addFeedback: "Thêm phản hồi",
    feedbackList: "Danh sách phản hồi",
    all: "Tất cả",
    resolve: "Giải quyết",
    noFeedbackFound: "Không tìm thấy phản hồi nào",

    // Reports
    reportGenerator: "Tạo báo cáo",
    generateReport: "Tạo báo cáo",
    configureReportSettings: "Cấu hình cài đặt báo cáo",
    reportType: "Loại báo cáo",
    dailyReport: "Báo cáo hàng ngày",
    dailyReportDesc: "Công việc và hoạt động trong ngày cụ thể",
    weeklyReport: "Báo cáo hàng tuần",
    weeklyReportDesc: "Tóm tắt hoạt động trong tuần",
    projectReport: "Báo cáo dự án",
    projectReportDesc: "Tổng quan toàn diện về dự án",
    feedbackReport: "Báo cáo phản hồi",
    feedbackReportDesc: "Phân tích phản hồi khách hàng",
    optional: "Tùy chọn",
    allProjects: "Tất cả dự án",
    fromDate: "Từ ngày",
    toDate: "Đến ngày",
    generateAndDownload: "Tạo & Tải xuống",
    customTemplate: "Mẫu tùy chỉnh",
    designCustomReportTemplate: "Thiết kế mẫu báo cáo riêng của bạn",
    templateName: "Tên mẫu",
    enterTemplateName: "Nhập tên mẫu",
    templateStructure: "Cấu trúc mẫu",
    templatePlaceholder: "Nhập cấu trúc mẫu tùy chỉnh...",
    availableVariables: "Biến có sẵn",
    projectDomain: "Tên miền dự án",
    taskStatus: "Trạng thái công việc",
    feedbackRating: "Đánh giá phản hồi",
    currentDate: "Ngày hiện tại",
    saveTemplate: "Lưu mẫu",

    // Report Generator enhancements
    manageTemplates: "Quản lý mẫu",
    templateDesigner: "Thiết kế mẫu",
    reportConfiguration: "Cấu hình báo cáo",
    exportOptions: "Tùy chọn xuất",
    chooseExportFormat: "Chọn định dạng xuất",
    basicData: "Dữ liệu cơ bản",
    advancedSpreadsheet: "Bảng tính nâng cao",
    documentReport: "Báo cáo tài liệu",
    printableReport: "Báo cáo in được",
    quickGenerate: "Tạo nhanh",
    generatePDFReport: "Tạo báo cáo PDF",
    generateExcelReport: "Tạo báo cáo Excel",
    manageYourReportTemplates: "Quản lý các mẫu báo cáo đã lưu",
    created: "Đã tạo",
    use: "Sử dụng",
    edit: "Chỉnh sửa",
    noTemplatesYet: "Chưa có mẫu nào được tạo",
    createCustomReportTemplate: "Tạo mẫu báo cáo tùy chỉnh",
    loadDefault: "Tải mặc định",
    basicVariables: "Biến cơ bản",
    projectVariables: "Biến dự án",
    loopVariables: "Biến lặp",
    loopThroughTasks: "Lặp qua tất cả công việc",
    loopThroughFeedbacks: "Lặp qua tất cả phản hồi",
    loopThroughProjects: "Lặp qua tất cả dự án",
    taskVariables: "Biến công việc",
    feedbackVariables: "Biến phản hồi",
    useTheseVariablesInTemplate: "Sử dụng các biến này trong mẫu",

    // Settings
    languageAndTheme: "Ngôn ngữ & Giao diện",
    customizeAppearance: "Tùy chỉnh giao diện ứng dụng",
    language: "Ngôn ngữ",
    theme: "Giao diện",
    light: "Sáng",
    dark: "Tối",
    system: "Hệ thống",
    customColors: "Màu tùy chỉnh",
    personalizeColors: "Cá nhân hóa bảng màu của bạn",
    primaryColor: "Màu chính",
    secondaryColor: "Màu phụ",
    accentColor: "Màu nhấn",
    backgroundColor: "Màu nền",
    applyColors: "Áp dụng màu",
    notifications: "Thông báo",
    manageNotificationSettings: "Quản lý tùy chọn thông báo",
    emailNotifications: "Thông báo Email",
    receiveEmailUpdates: "Nhận cập nhật qua email",
    desktopNotifications: "Thông báo Desktop",
    showDesktopAlerts: "Hiển thị cảnh báo desktop",
    feedbackNotifications: "Thông báo phản hồi",
    notifyNewFeedback: "Thông báo khi có phản hồi mới",
    taskNotifications: "Thông báo công việc",
    remindTaskDeadlines: "Nhắc nhở về deadline công việc",
    dataManagement: "Quản lý dữ liệu",
    backupAndRestore: "Sao lưu và khôi phục dữ liệu",
    exportData: "Xuất dữ liệu",
    importData: "Nhập dữ liệu",
    importFromFile: "Nhập từ file",
    dataImportedSuccessfully: "Dữ liệu đã được nhập thành công!",
    errorImportingData: "Lỗi khi nhập dữ liệu. Vui lòng kiểm tra định dạng file.",

    // Dashboard enhancements
    avgRating: "Đánh giá TB",
    across: "trên",
    requiresAttention: "Cần chú ý",
    highPriorityTasks: "công việc ưu tiên cao",
    urgent: "Khẩn cấp",
    review: "Xem xét",
    projectProgress: "Tiến độ dự án",
    recentActivity: "Hoạt động gần đây",
    noActiveProjects: "Không có dự án đang hoạt động",
    noRecentActivity: "Không có hoạt động gần đây",
    todaySchedule: "Lịch trình hôm nay",
    noTasksToday: "Không có công việc nào hôm nay",
    quickActions: "Thao tác nhanh",
    newAccount: "Tài khoản mới",

    // Report Generator enhancements
    manageTemplates: "Quản lý mẫu",
    templateDesigner: "Thiết kế mẫu",
    reportConfiguration: "Cấu hình báo cáo",
    exportOptions: "Tùy chọn xuất",
    chooseExportFormat: "Chọn định dạng xuất",
    basicData: "Dữ liệu cơ bản",
    advancedSpreadsheet: "Bảng tính nâng cao",
    documentReport: "Báo cáo tài liệu",
    printableReport: "Báo cáo in được",
    quickGenerate: "Tạo nhanh",
    generatePDFReport: "Tạo báo cáo PDF",
    generateExcelReport: "Tạo báo cáo Excel",
    manageYourReportTemplates: "Quản lý các mẫu báo cáo đã lưu",
    created: "Đã tạo",
    use: "Sử dụng",
    edit: "Chỉnh sửa",
    noTemplatesYet: "Chưa có mẫu nào được tạo",
    createCustomReportTemplate: "Tạo mẫu báo cáo tùy chỉnh",
    loadDefault: "Tải mặc định",
    basicVariables: "Biến cơ bản",
    projectVariables: "Biến dự án",
    loopVariables: "Biến lặp",
    loopThroughTasks: "Lặp qua tất cả công việc",
    loopThroughFeedbacks: "Lặp qua tất cả phản hồi",
    loopThroughProjects: "Lặp qua tất cả dự án",
    taskVariables: "Biến công việc",
    feedbackVariables: "Biến phản hồi",
    useTheseVariablesInTemplate: "Sử dụng các biến này trong mẫu",

    // Email Composer
    emailComposer: "Soạn Email",
    composeEmail: "Soạn Email",
    emailTemplates: "Mẫu Email",
    to: "Đến",
    cc: "CC",
    enterEmailSubject: "Nhập chủ đề email",
    emailContent: "Nội dung Email",
    enterEmailContent: "Nhập nội dung email",
    selectedAccounts: "Tài khoản đã chọn",
    sendEmail: "Gửi Email",
    attachReport: "Đính kèm báo cáo",
    includeAccounts: "Bao gồm tài khoản",
    selectAccountsToInclude: "Chọn tài khoản để bao gồm trong email",
    filterByProject: "Lọc theo dự án",
    noAccountsFound: "Không tìm thấy tài khoản",
    savedEmailTemplates: "Mẫu Email đã lưu",
    manageYourEmailTemplates: "Quản lý mẫu email của bạn",
    emailTemplateDesigner: "Thiết kế mẫu Email",
    createCustomEmailTemplate: "Tạo mẫu email tùy chỉnh",
    accountCredentials: "Thông tin tài khoản",
    generalEmail: "Email chung",
    clear: "Xóa",
    useTheseVariablesInEmail: "Sử dụng các biến này trong email",
    clientName: "Tên khách hàng",
    yourName: "Tên của bạn",
    accountVariables: "Biến tài khoản",
    accountInfo: "Thông tin tài khoản",
    reportVariables: "Biến báo cáo",
    progress: "Tiến độ",
    projectStatus: "Trạng thái dự án",
    recentTasks: "Công việc gần đây",
    nextSteps: "Bước tiếp theo",
    noEmailTemplatesYet: "Chưa có mẫu email nào được tạo",
    useTemplate: "Sử dụng mẫu",
  },
}

export function useLanguage() {
  const [language, setLanguage] = useState<"en" | "vi">("en")

  useEffect(() => {
    const savedLanguage = localStorage.getItem("language") as "en" | "vi"
    if (savedLanguage) {
      setLanguage(savedLanguage)
    }
  }, [])

  const changeLanguage = (newLanguage: "en" | "vi") => {
    setLanguage(newLanguage)
    localStorage.setItem("language", newLanguage)
  }

  const t = (key: string) => {
    return translations[language][key as keyof (typeof translations)[typeof language]] || key
  }

  return {
    language,
    setLanguage: changeLanguage,
    t,
  }
}
